### ISSUE TITLE
regex issue with "U.S."

### ISSUE THREAD

**Issue by wayfarerjing** [ian-beaver/pycontractions#10]
When there is a word "U.S." it is expanded to "you.S." which is obviously wrong. After looking at the code I think the regex part to identify "u" in a sentence should put spaces before and after "u". Instead of matching only "u" it should be looking for " u ". Does anyone think the same way? Hopefully this can be resolved.

Thank you!

**Comment by ian-beaver** [comment]
This is fixed in 2.0.1, thanks for catching this!
