### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by kallewesterling** [ian-beaver/pycontractions#12]
While trying to install pycontractions using `pip install` the following error occurs:

![image](https://user-images.githubusercontent.com/7298727/62488344-11029180-b792-11e9-88fe-2fab6eb5b266.png)

Any ideas how to solve this?

**Comment by ian-beaver** [comment]
This is actually a language-check issue.  To install pycontractions, Java 8 must be used until language-check fixes their installer script:

```
$ sudo apt install openjdk-8-jdk
$ sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
$ pip install language-check
$ pip install pycontractions
```

**Comment by kallewesterling** [comment]
Thank you!

**Comment by zluvsand** [comment]
I came across similar issue on Windows. Do you have the workaround script for windows too? (Equivalent to the one you provided on 2019-09-07)  Below is the screenshot from Anaconda prompt:
![image](https://user-images.githubusercontent.com/52989548/88160003-6ceb5200-cc51-11ea-937f-c2892962cff0.png)
The package looks really useful, btw. 👍
