### ISSUE TITLE
Word2Vec model not found - request for error instead of sys.exit

### ISSUE THREAD

**Issue by thisisnic** [ian-beaver/pycontractions#15]
Hi Ian, I've found the pycontractions package really useful - thanks for writing it! One issue I'm having is that when trying to use a local file for the w2v model, if the path is wrong, the code in the load_models method exits Python. I could be wrong here, but I think it may be more helpful to users to raise an exception instead - what do you think?

And if you agree, shall I submit a PR with this change I've proposed above?

**Comment by ian-beaver** [comment]
@thisisnic yes that was a hold over from this was just a stand alone script.  I changed the sys.exit to an AttributeError that calling applications can catch if they want.
