### ISSUE TITLE
regex issue with "were"

### ISSUE THREAD

**Issue by russbramblett** [ian-beaver/pycontractions#6]
Where there are cases of 'were' it is expanded to 'we are' because the regex looks for spelling errors associated with that contraction:.

recommend line 76 change from 
`re.compile(r"\bwe'?re\b", re.I | re.U): "we are",`
to
`re.compile(r"\bwe're\b", re.I | re.U): "we are",`

**Comment by ian-beaver** [comment]
This is fixed in 2.0.1, thanks for the feedback!
